services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/skill-tracker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      - mongodb
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5175:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  redis_data:
