import {
  IsMongoId,
  IsArray,
  ArrayMinSize,
  ArrayMaxSize,
  IsNumber,
} from "class-validator";
import { ApiProperty } from "@nestjs/swagger";

export class SubmitAssessmentDto {
  @ApiProperty({
    description: "The ID of the assessment object generated by the server",
    example: "699034c040ece1e038c74d11",
  })
  @IsMongoId()
  assessmentId: string;

  @ApiProperty({
    description: "The ID of the chapter the assessment belongs to",
    example: "699034c040ece1e038c74d10",
  })
  @IsMongoId()
  chapterId: string;

  @ApiProperty({
    description: "An array of selected answer indices (0-3)",
    example: [0, 2, 1, 3, 0],
    type: [Number],
    minItems: 3,
    maxItems: 5,
  })
  @IsArray()
  @ArrayMinSize(3)
  @ArrayMaxSize(5)
  @IsNumber({}, { each: true })
  answers: number[];
}

